### PR TITLE
Code analysis

### PR DESCRIPTION
**Pull request by dmill166**
Incorporated [GG Shield](https://docs.gitguardian.com/internal-repositories-monitoring/gg_shield/getting_started) from GitGuardian. Local requirements include:

1. Add local environment variable.
```
#~/.bash_profile
export GITGUARDIAN_API_KEY="PING_ME_FOR_THIS_TOKEN"
```

2. Install ggshield (I have it in the requirements & that may be easier).
`pip install -U ggshield
`
3. Two options:
  a. If you want to do a one-time, scan: `ggshield scan repo .`
  b. If you want to install the [pre-push hook](https://docs.gitguardian.com/internal-repositories-monitoring/integrations/git_hooks/pre_push) to inspect for secrets:
    i. `pip install pre-commit` (also in `requirements.txt`)
    ii. Create a `.pre-commit-config.yaml` file in the root of the project. (Taken care of by pulling this in)
    iii. Run `pre-commit install --hook-type pre-push` on your command-line for the project

Output looks like this (look for the `GitGuardian Shield (pre-commit)` line)
:
```
(venv) (base) dakotamiller@MacBook-Pro-2 PrestoPantry % git push
[WARNING] The 'rev' field of repo 'https://github.com/gitguardian/ggshield' appears to be a mutable reference (moving tag / branch).  Mutable references are never updated after first install and are not supported.  See https://pre-commit.com/#using-the-latest-version-for-a-repository for more details.  Hint: `pre-commit autoupdate` often fixes this.
[INFO] Installing environment for https://github.com/gitguardian/ggshield.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
GitGuardian Shield (pre-commit)..........................................Passed
Enumerating objects: 10, done.
Counting objects: 100% (10/10), done.
Delta compression using up to 8 threads
Compressing objects: 100% (6/6), done.
Writing objects: 100% (6/6), 1.08 KiB | 1.08 MiB/s, done.
Total 6 (delta 3), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (3/3), completed with 3 local objects.
To https://github.com/dmill166/PrestoPantry.git
   4f9f366..c7ffd20  code_analysis -> code_analysis
```

### CODE REVIEW

**Review by riley-strong — CHANGES_REQUESTED** [review]
I think when you ran `pip freeze` it included every pip package you have installed, not just the pip you were attempting to add.

**Comment by dmill166** [comment]
> I think when you ran `pip freeze` it included every pip package you have installed, not just the pip you were attempting to add.

I have a virtual environment for this project, so it should only be modules I've had to install to get it to work on Mac.

**Review by dmill166 — COMMENTED** [review]
@riley-strong  should be resolved now

**Review by riley-strong — APPROVED** [review]
:+1:  clean!

**Pull request merged**
